name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-web.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: "stable"

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Build Flutter Web (Production)
        working-directory: ./frontend
        run: |
          flutter build web \
            --release \
            --web-renderer canvaskit \
            --base-href /stock-market-websocket/ \
            --dart-define=dart.vm.product=true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend/build/web"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Optional: Build check for PRs (without deployment)
  build-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: "stable"

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Build Flutter Web (Check)
        working-directory: ./frontend
        run: |
          flutter build web \
            --release \
            --web-renderer canvaskit \
            --dart-define=dart.vm.product=true
